# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: github.com/moby/buildkit
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: github.com/docker/cli
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: github.com/docker/docker
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

      # TODO: require manual changes
      - dependency-name: go.opentelemetry.io/otel/exporters/otlp/otlptrace
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: go.opentelemetry.io/otel/sdk
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: go.opentelemetry.io/otel/trace
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: k8s.io/cli-runtime
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: k8s.io/kubectl
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: k8s.io/api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: bundler
    directory: "/docs"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: html-proofer
        update-types: ["version-update:semver-major"]
